language: objective-c
osx_image: xcode8.0

script:
- xcodebuild clean build test -project "NightViewSampleProject/NightViewSampleProject.xcodeproj" -scheme NightViewSampleProject -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 5S" ONLY_ACTIVE_ARCH=NO
